# Generated by Django 6.0.3 on 2026-04-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shorturl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalurl', models.TextField()),
                ('shortcode', models.CharField(max_length=10, unique=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('clickcount', models.IntegerField(default=0)),
            ],
        ),
    ]
